export const imgUrl=[
    {
        url:'https://m.media-amazon.com/images/I/51JnRKRH41L._MCnd_AC_.jpg'
    },
    {
        url:'https://m.media-amazon.com/images/I/41OdlwlaEeS._MCnd_AC_.jpg'
    },
    {
        url:'https://m.media-amazon.com/images/I/51u-IOXjzEL._MCnd_AC_.jpg'
    },
    {
        url:'https://m.media-amazon.com/images/I/81ix3yG1QDL._AC_SY135_.jpg'
    },
    {
        url:'https://m.media-amazon.com/images/I/71i-9XPZc5L._AC_SY135_.jpg'
    },
    {
        url:'https://m.media-amazon.com/images/I/81EgXbp4vaL._AC_SY135_.jpg'
    },
    {
        url:'https://m.media-amazon.com/images/I/81V5P1x+LSL._AC_SY135_.jpg'
    },
    {
        url:'https://images-eu.ssl-images-amazon.com/images/G/31/img23/Softlines_JWL_SH_GW_Assets/All_QC_JWLSSH/Aug_28/sports2-Low._SY116_CB596945057_.jpg'
    },
    {
        url:'https://images-eu.ssl-images-amazon.com/images/G/31/img23/Softlines_JWL_SH_GW_Assets/All_QC_JWLSSH/Aug_28/MS_low_res._SY116_CB596989025_.jpg'
    },
    {
        url:'https://images-eu.ssl-images-amazon.com/images/G/31/img23/Softlines_JWL_SH_GW_Assets/All_QC_JWLSSH/Aug_28/Heels_low_res._SY116_CB596989025_.jpg'
    },
    {
        url:'https://images-eu.ssl-images-amazon.com/images/G/31/img23/Softlines_JWL_SH_GW_Assets/All_QC_JWLSSH/Aug_28/HB_low_res._SY116_CB596989025_.jpg'
    } 
]